# Generated by Django 5.2.17 on 2026-09-25 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0004_backfill_inboxreply_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboxslaconfig",
            name="target_response_minutes",
            field=models.PositiveIntegerField(
                default=120, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
