# Generated by Django 5.2.17 on 2026-10-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0005_sla_target_minimum"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxreply",
            name="drafted_by",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=40
            ),
        ),
    ]
