# Generated by Django 5.2.17 on 2026-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0005_add_devto_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformcredential",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("instagram_login", "Instagram (Direct)"),
                    ("linkedin_personal", "LinkedIn (Personal Profile)"),
                    ("linkedin_company", "LinkedIn (Company Page)"),
                    ("tiktok", "TikTok"),
                    ("youtube", "YouTube"),
                    ("pinterest", "Pinterest"),
                    ("threads", "Threads"),
                    ("bluesky", "Bluesky"),
                    ("google_business", "Google Business Profile"),
                    ("mastodon", "Mastodon"),
                    ("devto", "DEV.to"),
                    ("x", "X (Twitter)"),
                ],
                max_length=30,
            ),
        ),
    ]
