# Generated by Django 5.2.17 on 2026-10-02 13:26

import apps.blog.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # The featured_image FK only needs the MediaAsset table, which exists from
    # media_library 0001. Depending on its latest migration instead would make
    # media_library's own migration tests (which rewind it to 0003) unapply
    # this app's tables.
    dependencies = [
        ("media_library", "0001_initial"),
        ("workspaces", "0004_require_dashboard_approval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "neopolis_static",
                                "Neopolis static site (publish-payload3)",
                            ),
                            ("morespace_static", "More Space static site (blog/)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "site_url",
                    models.URLField(
                        help_text="The live website, e.g. https://www.neopolisinfra.com"
                    ),
                ),
                (
                    "repo",
                    models.CharField(
                        help_text='GitHub repository, "owner/name".',
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$",
                                'Enter the repository as "owner/name".',
                            )
                        ],
                    ),
                ),
                ("branch", models.CharField(default="main", max_length=100)),
                (
                    "workflow_file",
                    models.CharField(
                        help_text="Workflow that deploys the site, e.g. publish3.yml",
                        max_length=200,
                    ),
                ),
                (
                    "netlify_site_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_sites",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "blog_site",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.CharField(
                        max_length=100, validators=[apps.blog.models.validate_slug]
                    ),
                ),
                ("excerpt", models.TextField(blank=True, default="", max_length=400)),
                (
                    "body",
                    models.TextField(blank=True, default="", help_text="Markdown."),
                ),
                (
                    "featured_image_alt",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("seo_title", models.CharField(blank=True, default="", max_length=60)),
                (
                    "meta_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("category", models.CharField(blank=True, default="", max_length=60)),
                (
                    "faq",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of {"q": ..., "a": ...}.',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Awaiting approval"),
                            ("changes_requested", "Changes requested"),
                            ("approved", "Approved"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "approved_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "approved_revision",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("published_url", models.URLField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("published_card", models.JSONField(blank=True, default=dict)),
                ("commit_sha", models.CharField(blank=True, default="", max_length=64)),
                ("deploy_run_id", models.BigIntegerField(blank=True, null=True)),
                ("deploy_run_url", models.URLField(blank=True, default="")),
                (
                    "deploy_status",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("publish_attempts", models.PositiveIntegerField(default=0)),
                ("publish_started_at", models.DateTimeField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to="media_library.mediaasset",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="blog.blogsite",
                    ),
                ),
            ],
            options={
                "db_table": "blog_post",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogPostEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("edited", "Edited"),
                            ("submitted", "Submitted for approval"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes requested"),
                            ("approval_withdrawn", "Approval withdrawn"),
                            ("publish_started", "Publishing started"),
                            ("committed", "Committed to the website repository"),
                            ("deploy_succeeded", "Deploy succeeded"),
                            ("deploy_failed", "Deploy failed"),
                            ("verified", "Verified live"),
                            ("publish_failed", "Publishing failed"),
                            ("social_drafts_created", "Social drafts created"),
                        ],
                        max_length=40,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="blog.blogpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "blog_post_event",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["post", "-created_at"],
                        name="blog_post_e_post_id_514334_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="blogsite",
            constraint=models.UniqueConstraint(
                fields=("workspace", "repo"), name="blog_site_unique_repo_per_workspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="blogpost",
            constraint=models.UniqueConstraint(
                fields=("site", "slug"), name="blog_post_unique_slug_per_site"
            ),
        ),
    ]
