# Generated by Django 5.2.17 on 2026-10-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="cover_style",
            field=models.CharField(
                choices=[
                    (
                        "designed",
                        "Designed cover: the title set over the picture in the brand's look",
                    ),
                    (
                        "plain",
                        "Plain: the featured image as uploaded (no image, no hero)",
                    ),
                ],
                db_default="designed",
                default="designed",
                max_length=20,
            ),
        ),
    ]
