# Generated by Django 5.2.17 on 2026-10-09 15:23

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_cover_style"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="focus_keyword",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=80
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="secondary_keywords",
            field=models.JSONField(
                blank=True,
                db_default=models.Value([], output_field=models.JSONField()),
                default=list,
                help_text="Related search terms.",
            ),
        ),
        migrations.CreateModel(
            name="SearchConsoleConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "property_url",
                    models.CharField(
                        help_text='The Search Console property, e.g. "sc-domain:neopolisinfra.com".',
                        max_length=300,
                    ),
                ),
                (
                    "refresh_token",
                    apps.common.encryption.EncryptedTextField(blank=True, default=""),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_console",
                        to="blog.blogsite",
                    ),
                ),
            ],
            options={
                "db_table": "blog_search_console_connection",
            },
        ),
        migrations.CreateModel(
            name="SearchPerformance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("page", models.URLField(max_length=500)),
                ("query", models.CharField(max_length=300)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("ctr", models.FloatField(default=0)),
                ("position", models.FloatField(default=0)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_performance",
                        to="blog.blogsite",
                    ),
                ),
            ],
            options={
                "db_table": "blog_search_performance",
                "indexes": [
                    models.Index(
                        fields=["site", "page", "date"],
                        name="idx_search_perf_site_page",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "date", "page", "query"),
                        name="blog_search_perf_unique_row",
                    )
                ],
            },
        ),
    ]
