# Generated by Django 5.2.17 on 2026-10-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0003_alter_approvalaction_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalaction",
            name="channel",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="approvalaction",
            name="fingerprint",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="approvalaction",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="approvalaction",
            name="revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="approvalaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("changes_requested", "Changes Requested"),
                    ("rejected", "Rejected"),
                    ("resubmitted", "Resubmitted"),
                    ("held", "Hold Requested"),
                    ("time_approved", "Publish Time Approved"),
                    ("approval_withdrawn", "Approval Withdrawn"),
                    ("publish_blocked", "Publish Blocked"),
                ],
                max_length=20,
            ),
        ),
    ]
