# Generated by Django 5.2.17 on 2026-09-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0005_alter_customcalendarevent_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurrencerule",
            name="generated_dates",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
