# Generated by Django 5.2.17 on 2026-10-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0003_alter_workspace_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="require_dashboard_approval",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
