# Generated by Django 5.2.17 on 2026-10-08 09:13

import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("composer", "0023_approval_gate"),
        ("media_library", "0005_unguessable_upload_paths"),
        ("social_accounts", "0020_seed_x_platform_rows"),
        ("workspaces", "0004_require_dashboard_approval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brand_name", models.CharField(max_length=100)),
                (
                    "about",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="One or two sentences: what the company does, for whom.",
                        max_length=500,
                    ),
                ),
                (
                    "audience",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Who the posts are for, and what they care about.",
                    ),
                ),
                (
                    "voice",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Tone of voice, in a few lines.",
                    ),
                ),
                (
                    "facts",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Facts the team may use: offerings, projects, numbers, contact details, links. The agents state nothing that isn't here or in the idea.",
                    ),
                ),
                (
                    "dos",
                    models.TextField(blank=True, default="", help_text="Always do."),
                ),
                (
                    "donts",
                    models.TextField(blank=True, default="", help_text="Never do."),
                ),
                (
                    "compliance",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Legal or regulatory rules, e.g. registration numbers or disclaimers.",
                    ),
                ),
                (
                    "default_cta",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The usual call to action.",
                        max_length=200,
                    ),
                ),
                ("website", models.URLField(blank=True, default="")),
                (
                    "hashtags",
                    models.JSONField(
                        blank=True, default=list, help_text="Hashtags the brand uses."
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#081D4A",
                        max_length=7,
                        validators=[apps.common.validators.validate_hex_color],
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#FF6600",
                        max_length=7,
                        validators=[apps.common.validators.validate_hex_color],
                    ),
                ),
                (
                    "display_font",
                    models.CharField(
                        choices=[
                            ("oswald", "Oswald — condensed and bold"),
                            ("outfit", "Outfit — geometric and modern"),
                        ],
                        default="oswald",
                        max_length=20,
                    ),
                ),
                (
                    "wordmark",
                    models.CharField(
                        help_text="The name as it is set on graphics, e.g. NEOPOLIS INFRA.",
                        max_length=60,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Shown at the foot of graphics.",
                        max_length=100,
                    ),
                ),
                (
                    "photo_style",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What the pictures look like: subject matter, light, lens, mood.",
                    ),
                ),
                (
                    "default_template",
                    models.CharField(
                        choices=[
                            (
                                "editorial",
                                "Editorial — the picture full-bleed, the headline over it",
                            ),
                            ("split", "Split — the picture above, a brand panel below"),
                            ("statement", "Statement — bold type on the brand colour"),
                            (
                                "stat",
                                "Stat card — one big number, with a picture strip",
                            ),
                        ],
                        default="editorial",
                        max_length=20,
                    ),
                ),
                (
                    "default_format",
                    models.CharField(
                        choices=[
                            (
                                "portrait",
                                "Portrait 4:5 (1080×1350) — most room in the feed",
                            ),
                            ("square", "Square 1:1 (1080×1080)"),
                            ("landscape", "Landscape 1.91:1 (1200×628)"),
                        ],
                        default="portrait",
                        max_length=20,
                    ),
                ),
                (
                    "default_grade",
                    models.CharField(
                        choices=[
                            ("natural", "Natural colour"),
                            (
                                "brand_tint",
                                "Brand tint — pictures pulled towards the brand colour",
                            ),
                            ("duotone", "Duotone in the brand colours"),
                            ("mono", "Black and white"),
                        ],
                        default="brand_tint",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. A PNG with a transparent background works best; without it the wordmark is set in type.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media_library.mediaasset",
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_profile",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "studio_brand_profile",
            },
        ),
        migrations.CreateModel(
            name="StudioBrief",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idea", models.TextField()),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("awareness", "Build awareness"),
                            ("education", "Teach something useful"),
                            ("engagement", "Start a conversation"),
                            ("leads", "Get enquiries"),
                            ("announcement", "Announce news"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "style_lock",
                    models.BooleanField(
                        default=True,
                        help_text="Design the graphic in the same look as the last post this workspace made.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("working", "The team is working"),
                            ("ready", "Ready for approval"),
                            ("approved", "Approved"),
                            ("failed", "Failed"),
                            ("discarded", "Discarded"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("strategy", "Strategist"),
                            ("copy", "Copywriter"),
                            ("art", "Art director"),
                            ("picture", "Illustrator"),
                            ("render", "Designer"),
                            ("review", "Brand reviewer"),
                            ("handoff", "Producer"),
                            ("done", "Done"),
                        ],
                        default="strategy",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The latest change request, if any.",
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "auto_revisions",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Revisions the brand reviewer asked for in this revision (capped).",
                    ),
                ),
                (
                    "regenerate_picture",
                    models.BooleanField(
                        default=False,
                        help_text="Paint a new picture on the next pass instead of keeping the current one.",
                    ),
                ),
                ("post_copy", models.JSONField(blank=True, default=dict)),
                ("design_spec", models.JSONField(blank=True, default=dict)),
                ("review_notes", models.JSONField(blank=True, default=dict)),
                ("style_reference", models.JSONField(blank=True, default=dict)),
                ("proposed_publish_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="studio_briefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graphic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media_library.mediaasset",
                    ),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media_library.mediaasset",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="studio_briefs",
                        to="composer.post",
                    ),
                ),
                (
                    "social_accounts",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="social_accounts.socialaccount"
                    ),
                ),
                (
                    "source_picture",
                    models.ForeignKey(
                        blank=True,
                        help_text="A photo from the media library to use instead of a generated picture.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media_library.mediaasset",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studio_briefs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "studio_brief",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "agent",
                    models.CharField(
                        choices=[
                            ("strategist", "Strategist"),
                            ("copywriter", "Copywriter"),
                            ("art_director", "Art director"),
                            ("illustrator", "Illustrator"),
                            ("designer", "Designer"),
                            ("reviewer", "Brand reviewer"),
                            ("producer", "Producer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Working"),
                            ("succeeded", "Done"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(blank=True, default="", max_length=500)),
                ("output", models.JSONField(blank=True, default=dict)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="studio.studiobrief",
                    ),
                ),
            ],
            options={
                "db_table": "studio_agent_run",
                "ordering": ["started_at"],
            },
        ),
        migrations.CreateModel(
            name="StudioConcept",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("hook", models.TextField()),
                ("angle", models.TextField(blank=True, default="")),
                ("key_points", models.JSONField(blank=True, default=list)),
                (
                    "post_format",
                    models.CharField(
                        choices=[
                            ("single_image", "Single image"),
                            ("stat", "A number that matters"),
                            ("quote", "Point of view"),
                            ("tips", "Tips or checklist"),
                            ("announcement", "Announcement"),
                        ],
                        default="single_image",
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField(blank=True, default="")),
                ("recommended", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="studio.studiobrief",
                    ),
                ),
                (
                    "saved_idea",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="composer.idea",
                    ),
                ),
            ],
            options={
                "db_table": "studio_concept",
                "ordering": ["revision", "position"],
            },
        ),
        migrations.AddField(
            model_name="studiobrief",
            name="chosen_concept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="studio.studioconcept",
            ),
        ),
        migrations.AddIndex(
            model_name="studiobrief",
            index=models.Index(
                fields=["workspace", "status"], name="idx_studio_brief_ws_status"
            ),
        ),
    ]
