# Generated by Django 5.2.17 on 2026-10-09 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_seo_keywords_search_console"),
        ("composer", "0023_approval_gate"),
        ("media_library", "0005_unguessable_upload_paths"),
        ("social_accounts", "0020_seed_x_platform_rows"),
        ("studio", "0001_initial"),
        ("workspaces", "0004_require_dashboard_approval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "autopilot_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Plan and prepare next week's posts every week. Every post still needs approval.",
                    ),
                ),
                ("posts_per_week", models.PositiveSmallIntegerField(default=5)),
                (
                    "pillars",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Themes the planner rotates between.",
                    ),
                ),
                (
                    "plan_weekday",
                    models.PositiveSmallIntegerField(
                        default=4, help_text="0 is Monday. The default is Friday."
                    ),
                ),
                (
                    "plan_hour",
                    models.PositiveSmallIntegerField(
                        default=16, help_text="Hour of day in the workspace timezone."
                    ),
                ),
                ("blog_posts_per_month", models.PositiveSmallIntegerField(default=0)),
                (
                    "monthly_budget_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=150,
                        help_text="The team starts no new model work past this.",
                        max_digits=8,
                    ),
                ),
                (
                    "learn_from_best",
                    models.BooleanField(
                        default=False,
                        help_text="Let the art director start from your best creatives and references, not only the last post.",
                    ),
                ),
                (
                    "inbox_drafts_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Draft replies to new comments, messages and reviews for a person to send.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "studio_agency_settings",
            },
        ),
        migrations.CreateModel(
            name="AutopilotWeek",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "week_start",
                    models.DateField(
                        help_text="The Monday of the week being planned, in the workspace timezone."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("planned", "Planned"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "studio_autopilot_week",
                "ordering": ["-week_start"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("client", "With the client"),
                            ("internal", "Internal"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "studio_conversation",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreativeInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform", models.CharField(blank=True, default="", max_length=40)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("studio", "Made by the team"),
                            ("external", "Made elsewhere"),
                            ("upload", "Uploaded reference"),
                        ],
                        default="external",
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("ratio", models.FloatField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("caption", models.TextField(blank=True, default="")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The curator's description of the look.",
                    ),
                ),
                (
                    "is_reference",
                    models.BooleanField(
                        default=False, help_text="A person picked it: learn from this."
                    ),
                ),
                (
                    "reference_note",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("described_at", models.DateTimeField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "studio_creative_insight",
                "ordering": ["-is_reference", "-score", "-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "author_kind",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("staff", "Team member"),
                            ("agent", "Agent"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("agent", models.CharField(blank=True, default="", max_length=40)),
                ("body", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="A note for the team only; never shown to a client, even in a client thread.",
                    ),
                ),
                ("action", models.CharField(blank=True, default="", max_length=30)),
                (
                    "action_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No action"),
                            ("done", "Done"),
                            ("started", "The team is on it"),
                            ("needs_human", "Waiting for a person"),
                            ("declined", "Not possible"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "studio_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="agentrun",
            name="effort",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="fallback_used",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="stage",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_runs",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="brandprofile",
            name="house_style",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="The look of your best work in a few lines, written by the creative memory curator from your references and best-performing posts. You can edit it; the art director and prompt engineer use it.",
            ),
        ),
        migrations.AddField(
            model_name="brandprofile",
            name="house_style_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studiobrief",
            name="origin",
            field=models.CharField(
                choices=[
                    ("manual", "Briefed by a person"),
                    ("autopilot", "Planned by autopilot"),
                    ("chat", "Asked for in the team thread"),
                    ("repurpose", "Made from a blog article"),
                ],
                db_default="manual",
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studiobrief",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who asked for it, when that isn't the author (for example a client in the team thread).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="agent",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="brief",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="studio.studiobrief",
            ),
        ),
        migrations.AlterField(
            model_name="studiobrief",
            name="stage",
            field=models.CharField(
                choices=[
                    ("strategy", "Strategist"),
                    ("copy", "Copywriter"),
                    ("art", "Art director"),
                    ("picture", "Illustrator"),
                    ("render", "Designer"),
                    ("review", "Brand reviewer"),
                    ("channel", "Channel editor"),
                    ("qa", "QA inspector"),
                    ("schedule", "Scheduler"),
                    ("handoff", "Producer"),
                    ("done", "Done"),
                ],
                default="strategy",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studiobrief",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned — waiting its turn"),
                    ("queued", "Queued"),
                    ("working", "The team is working"),
                    ("ready", "Ready for approval"),
                    ("approved", "Approved"),
                    ("failed", "Failed"),
                    ("discarded", "Discarded"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AgencyJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("plan", "Weekly plan"),
                            ("blog", "Blog article"),
                            ("chat", "Reply in the team thread"),
                            ("inbox", "Inbox reply drafts"),
                            ("report", "Client report"),
                            ("learn", "Creative memory refresh"),
                            ("repurpose", "Posts from an article"),
                            ("seo", "SEO check-up"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("working", "Working"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("stage", models.CharField(blank=True, default="", max_length=30)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("input", models.JSONField(blank=True, default=dict)),
                ("state", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "blog_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agency_jobs",
                        to="blog.blogpost",
                    ),
                ),
                (
                    "brief",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="studio.studiobrief",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="studio.agencyjob",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agency_jobs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "studio_agency_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="agentrun",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="studio.agencyjob",
            ),
        ),
        migrations.AddField(
            model_name="studiobrief",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="The plan, chat or article job that asked for this brief.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="briefs",
                to="studio.agencyjob",
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["workspace", "started_at"], name="idx_agent_run_ws_started"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("brief__isnull", False), ("job__isnull", False), _connector="OR"
                ),
                name="agent_run_has_brief_or_job",
            ),
        ),
        migrations.AddField(
            model_name="agencysettings",
            name="accounts",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="social_accounts.socialaccount"
            ),
        ),
        migrations.AddField(
            model_name="agencysettings",
            name="blog_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="blog.blogsite",
            ),
        ),
        migrations.AddField(
            model_name="agencysettings",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                help_text="Drafts the team makes on its own carry this person's name. An owner or manager.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agencysettings",
            name="workspace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agency_settings",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="autopilotweek",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="studio.agencyjob",
            ),
        ),
        migrations.AddField(
            model_name="autopilotweek",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autopilot_weeks",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="blog_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="blog.blogpost",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="brief",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="studio.studiobrief",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="composer.post",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="agencyjob",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="studio.conversation",
            ),
        ),
        migrations.AddField(
            model_name="creativeinsight",
            name="media_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="media_library.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="creativeinsight",
            name="platform_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="composer.platformpost",
            ),
        ),
        migrations.AddField(
            model_name="creativeinsight",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="composer.post",
            ),
        ),
        migrations.AddField(
            model_name="creativeinsight",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="social_accounts.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="creativeinsight",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creative_insights",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="studio.conversation",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="studio.agencyjob",
            ),
        ),
        migrations.AddConstraint(
            model_name="autopilotweek",
            constraint=models.UniqueConstraint(
                fields=("workspace", "week_start"),
                name="autopilot_week_unique_per_workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["workspace", "audience"], name="idx_conversation_ws_audience"
            ),
        ),
        migrations.AddIndex(
            model_name="agencyjob",
            index=models.Index(
                fields=["workspace", "status"], name="idx_agency_job_ws_status"
            ),
        ),
        migrations.AddIndex(
            model_name="agencyjob",
            index=models.Index(
                fields=["kind", "status"], name="idx_agency_job_kind_status"
            ),
        ),
        migrations.AddIndex(
            model_name="creativeinsight",
            index=models.Index(
                fields=["workspace", "is_reference", "score"],
                name="idx_creative_ws_ref_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="creativeinsight",
            constraint=models.UniqueConstraint(
                condition=models.Q(("platform_post__isnull", False)),
                fields=("workspace", "platform_post"),
                name="creative_insight_unique_platform_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="creativeinsight",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("media_asset__isnull", False), ("platform_post__isnull", True)
                ),
                fields=("workspace", "media_asset"),
                name="creative_insight_unique_upload",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"], name="idx_message_conv_created"
            ),
        ),
    ]
