# Generated by Django 5.2.17 on 2026-09-27 06:46

import apps.media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0004_folder_root_names_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="file",
            field=models.FileField(
                max_length=255, upload_to=apps.media_library.models.asset_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                max_length=255,
                upload_to=apps.media_library.models.thumbnail_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="mediaassetversion",
            name="file",
            field=models.FileField(
                max_length=255, upload_to=apps.media_library.models.version_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="mediaassetversion",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="",
                max_length=255,
                upload_to=apps.media_library.models.thumbnail_upload_to,
            ),
        ),
    ]
