# Generated by Django 5.2.17 on 2026-09-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_notificationdelivery_batch_claimed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="shown_in_app",
            field=models.BooleanField(default=True),
        ),
    ]
